" following assignment concerns the numpy.random package in Python [2]. You are
required to create a Jupyter [5] notebook explaining the use of the package, including
detailed explanations of at least five of the distributions provided for in the package.
There are four distinct tasks to be carried out in your Jupyter notebook.
1. Explain the overall purpose of the package.

    Explained in basic what the package is used for 
    
    
2. Explain the use of the “Simple random data” and “Permutations” functions.
    Permutations done


3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers."






# Numpy.random package 

***



In [13]:
import numpy as np

from numpy.random import default_rng
rng = default_rng()

NumPy is an open-source package used by data scientists and is the universal standard for working with, and manipulating numerical data in Python.The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.
There are a number of distinct functions within the package that perform a wide variety of high- level mathematical operations on multidimensional numerical arrays. In recent years Numpy has become particularly important for machine learning and deep learning, as these often involve large datasets of numerical data. The cleaning and reshaping of data is a large part of the workflow when dealing with these datasets and nupmy can provide some excellent tools to aid in this data manipulation[1]  [4]
Among these functions is the numpy.random package which can generate pseudo-random numbers. This is useful for many aspects of data analytics and machine learning projects, from randomly initialing weights in an artificial neural network, splitting data into random sets, or randomly shuffling your dataset, being able to generate random numbers (actually, repeatable pseudo-random numbers) is essential. **Random sampling is used in many tasks related to data analysis, statistics and other related fields, and is very commonly seen in probability, Bayesian statistics (“Bayesian statistics is a mathematical procedure that applies probabilities to statistical problems. It provides people the tools to update their beliefs in the evidence of new data.”), machine learning, among others  (Check this sentence out for improvements)**



While python's in-built random package ```random``` can generate values, for larger arrays ```numpy.random``` is preferred as it can sample more than one value at a time. This isn't so much an issue for smaller arrays, but for larger there is a noticeably faster time differential in most cases.[3] The numpy package can also offer a few extra probability distributions, such as binomial, commonly used in scientific research, as well as a couple of convenience functions for generating arrays of random data. The random.random library is a little more lightweight, and generally not considered suitable for scientific research or other kinds of work in statistics. [2] 










***
## Simple random data



## Permutations

The permutations functions in Numpy  consist of 2 very similar functions: ```shuffle(x)``` and ```permutation (x)```. The documentation has changed on this slightly since the 1.21 release in June 2021 and now provides functionality to manipulate the sub-arrays by calling ```axis```.
Prior to the newest release of NumPy the method for calling these functions was through ```np.random.shuffle(x)``` or ```np.random.permutation(x)```; however since release 1.21 in June 2021 [7] the accepted method is now to import ```rng``` from the random package, as seen above, and use this in the function call instead. As of October 2021 the older method of calling this function is still working, but new users should be aware that this may become deprecated in the future.   


### Shuffle (x, axis = 0)
The shuffle function modifies an array sequence in-place by shuffling its contents. It should be noted that this function will only shuffle the first axis of a multi-dimensional array (ie an array with more than one sub-arrays) by default. Since June 2021. shuffle now uses ```axis``` as an argument to manipulate the sub-arrays, ie if axis is set at 0 then only the first dimension of arrays will shuffle around. However if it is set to 1 or any other sub-array level, then the first level will set as they were and it is only the values in the dimension called that will move. As this can be a difficult thing to abstractly visualise, I have laid out the following examples below to help visualise the dimensions. 





In [16]:
#Create a sample array from 0-9 inclusive 
arr= np.arange(10)
print (arr)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
#Using the random.shuffle function.

rng.shuffle(arr)

print (arr) 

[0 8 2 1 9 5 4 6 7 3]


In [62]:
#Creating a 6 x 3 array to demonstrate the axis function

arr = np.arange(18).reshape((6, 3))

print (arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [60]:
#As there is no axis argument called, shuffle defaults to 0
rng.shuffle (arr, axis = 0)

print (arr)

[[ 9 10 11]
 [15 16 17]
 [ 6  7  8]
 [12 13 14]
 [ 0  1  2]
 [ 3  4  5]]


In [ ]:
arr = np.arange(18).reshape((6, 3))

print (arr)

In [61]:
rng.shuffle (arr, axis =1)

print (arr)

[[10 11  9]
 [16 17 15]
 [ 7  8  6]
 [13 14 12]
 [ 1  2  0]
 [ 4  5  3]]


### Permutation (x, axis = 0)
Is the act or process of changing the linear order of an ordered set. permutation(x) returns a random permutation of a sequence, or return a permuted range. If ```x``` is an array, it creates a copy of the original and shuffles those elements randomly. As with ```shuffle``` above, if it a multi-dimensional array then only the first dimension of the array is shuffled by default, however the use of ```axis``` will determine which array is shuffled, defaulting as axis 0. 

In [31]:
#arr is created from the example above. 
print (arr)


[0 1 2 3 4 5 6 7 8 9]


In [34]:
#demonstrates the usage of permutation.
rng.permutation(arr)

array([6, 0, 1, 5, 9, 3, 4, 7, 8, 2])

In [45]:
#Create original array
arr= np.arange(18). reshape((6,3))
print (arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [46]:
#Demonstrate permutation on axis 0
rng.permutation (arr)

array([[ 6,  7,  8],
       [ 0,  1,  2],
       [15, 16, 17],
       [ 3,  4,  5],
       [ 9, 10, 11],
       [12, 13, 14]])

In [49]:
#Demonstrate permutation on axis 1
rng.permutation (arr, axis =  1)

array([[ 1,  0,  2],
       [ 4,  3,  5],
       [ 7,  6,  8],
       [10,  9, 11],
       [13, 12, 14],
       [16, 15, 17]])

Note that in the example of permutation on axis 1 the positioning of the original numbers within each sub-array are the only thing that shuffled, leaving the positioning of the arrays in the overall list as it was when the object was originally created

Numpy’s random number routines produce pseudo random numbers using combinations of a BitGenerator to create sequences and a Generator to use those sequences to sample from different statistical distributions:

BitGenerators: Objects that generate random numbers. These are typically unsigned integer words filled with sequences of either 32 or 64 random bits.

Generators: Objects that transform sequences of random bits from a BitGenerator into sequences of numbers that follow a specific probability distribution (such as uniform, Normal or Binomial) within a specified interval.

Since Numpy version 1.17.0 the Generator can be initialized with a number of different BitGenerators. It exposes many different probability distributions. See NEP 19 for context on the updated random Numpy number routines. The legacy RandomState random number routines are still available, but limited to a single BitGenerator. See What’s New or Different for a complete list of improvements and differences from the legacy RandomState.

For convenience and backward compatibility, a single RandomState instance’s methods are imported into the numpy.random namespace, see Legacy Random Generation for the complete list.

# END
***

## References 

[1]: https://numpy.org/doc/stable/user/absolute_beginners.html#generating-random-numbers

[2]: https://stackoverflow.com/questions/7029993/differences-between-numpy-random-and-random-random-in-python

[3]: wes mckinney's book pg 120

[4]: https://www.sharpsightlabs.com/blog/numpy-random-choice/

[5]: https://www.analyticsvidhya.com/blog/2016/06/bayesian-statistics-beginners-simple-english/

[6]: https://numpy.org/doc/stable/reference/random/generated/numpy.random.shuffle.html

[7]: https://github.com/numpy/numpy/milestone/87

[8]: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.permutation.html#numpy.random.Generator.permutation

[9]: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.shuffle.html#numpy.random.Generator.shuffle



https://www.qualtrics.com/uk/experience-management/research/simple-random-sampling/




