" following assignment concerns the numpy.random package in Python [2]. You are
required to create a Jupyter [5] notebook explaining the use of the package, including
detailed explanations of at least five of the distributions provided for in the package.
There are four distinct tasks to be carried out in your Jupyter notebook.
1. Explain the overall purpose of the package.

    Explained in basic what the package is used for 
    
    
2. Explain the use of the “Simple random data” and “Permutations” functions.
    Permutations done


3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers."






# Numpy.random package 

***



In [71]:
import numpy as np

from numpy.random import default_rng
rng = default_rng()

NumPy is an open-source package used by data scientists and is the universal standard for working with, and manipulating numerical data in Python.The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.
There are a number of distinct functions within the package that perform a wide variety of high- level mathematical operations on multidimensional numerical arrays. In recent years Numpy has become particularly important for machine learning and deep learning, as these often involve large datasets of numerical data. The cleaning and reshaping of data is a large part of the workflow when dealing with these datasets and nupmy can provide some excellent tools to aid in this data manipulation[1]  [4]
Among these functions is the numpy.random package which can generate pseudo-random numbers. This is useful for many aspects of data analytics and machine learning projects, from randomly initialing weights in an artificial neural network, splitting data into random sets, or randomly shuffling your dataset, being able to generate random numbers (actually, repeatable pseudo-random numbers) is essential. **Random sampling is used in many tasks related to data analysis, statistics and other related fields, and is very commonly seen in probability, Bayesian statistics (“Bayesian statistics is a mathematical procedure that applies probabilities to statistical problems. It provides people the tools to update their beliefs in the evidence of new data.”), machine learning, among others  (Check this sentence out for improvements)**



While python's in-built random package ```random``` can generate values, for larger arrays ```numpy.random``` is preferred as it can sample more than one value at a time. This isn't so much an issue for smaller arrays, but for larger there is a noticeably faster time differential in most cases.[3] The numpy package can also offer a few extra probability distributions, such as binomial, commonly used in scientific research, as well as a couple of convenience functions for generating arrays of random data. The random.random library is a little more lightweight, and generally not considered suitable for scientific research or other kinds of work in statistics. [2] 


## Simple random data
*** 


**Simple random data in v1.16:** 


- rand(d0, d1, …, dn)	Random values in a given shape.
- randn(d0, d1, …, dn)	Return a sample (or samples) from the “standard normal” distribution.
- randint(low[, high, size, dtype])	Return random integers from low (inclusive) to high (exclusive).
- random([size])	Return random floats in the half-open interval [0.0, 1.0).
- numpy.random.random_sample
- choice(a[, size, replace, p])	Generates a random sample from a given 1-D array
bytes(length)	Return random bytes.


### numpy.random.rand
***
random.rand(d0, d1, ..., dn)
Random values in a given shape.

Note

This is a convenience function for users porting code from Matlab, and wraps random_sample. That function takes a tuple to specify the size of the output, which is consistent with other NumPy functions like numpy.zeros and numpy.ones.

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

Parameters
d0, d1, …, dnint, optional
The dimensions of the returned array, must be non-negative. If no argument is given a single Python float is returned.

Returns
outndarray, shape (d0, d1, ..., dn)
Random values.




       
 

In [72]:
np.random.rand(3,2)

array([[0.75942092, 0.51802332],
       [0.65741171, 0.46684917],
       [0.00177698, 0.42708268]])

### numpy.random.randn
***
random.randn(d0, d1, ..., dn)
Return a sample (or samples) from the “standard normal” distribution.

Note

This is a convenience function for users porting code from Matlab, and wraps standard_normal. That function takes a tuple to specify the size of the output, which is consistent with other NumPy functions like numpy.zeros and numpy.ones.

Note

New code should use the standard_normal method of a default_rng() instance instead; please see the Quick Start.

If positive int_like arguments are provided, randn generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1. A single float randomly sampled from the distribution is returned if no argument is provided.

Parameters
d0, d1, …, dnint, optional
The dimensions of the returned array, must be non-negative. If no argument is given a single Python float is returned.

Returns
Zndarray or float
A (d0, d1, ..., dn)-shaped array of floating-point samples from the standard normal distribution, or a single such float if no parameters were supplied.

See also

standard_normal
Similar, but takes a tuple as its argument.

normal
Also accepts mu and sigma arguments.

Generator.standard_normal
which should be used for new code.

Notes

For random samples from , use:

sigma * np.random.randn(...) + mu



In [73]:
np.random.randn()

-0.1313396345515561

In [74]:
#Two-by-four array of samples from N(3, 6.25):

3 + 2.5 * np.random.randn(2, 4)

array([[1.30840679, 4.4382527 , 0.85689875, 4.37939445],
       [5.66179456, 4.08784427, 4.65951461, 2.85148692]])

### numpy.random.Generator.integers
***

random.randint(low, high=None, size=None, dtype=int)
Return random integers from low (inclusive) to high (exclusive).

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

Note

New code should use the integers method of a default_rng() instance instead; please see the Quick Start.

Parameters
lowint or array-like of ints
Lowest (signed) integers to be drawn from the distribution (unless high=None, in which case this parameter is one above the highest such integer).

highint or array-like of ints, optional
If provided, one above the largest (signed) integer to be drawn from the distribution (see above for behavior if high=None). If array-like, must contain integer values

sizeint or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

dtypedtype, optional
Desired dtype of the result. Byteorder must be native. The default value is int.

New in version 1.11.0.

Returns
outint or ndarray of ints
size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.

See also

random_integers
similar to randint, only for the closed interval [low, high], and 1 is the lowest value if high is omitted.

Generator.integers
which should be used for new code.

       

### numpy.random.random_integers¶
random.random_integers(low, high=None, size=None)
Random integers of type np.int_ between low and high, inclusive.

Return random integers of type np.int_ from the “discrete uniform” distribution in the closed interval [low, high]. If high is None (the default), then results are from [1, low]. The np.int_ type translates to the C long integer type and its precision is platform dependent.

**This function has been deprecated.** Use randint instead.

Deprecated since version 1.11.0.


numpy.random.Generator.integers
numpy.random.Generator.integers
andom.Generator.integers(low, high=None, size=None, dtype=np.int64, endpoint=False)
Return random integers from low (inclusive) to high (exclusive), or if endpoint=True, low (inclusive) to high (inclusive). Replaces RandomState.randint (with endpoint=False) and RandomState.random_integers (with endpoint=True)

Return random integers from the “discrete uniform” distribution of the specified dtype. If high is None (the default), then results are from 0 to low.

Parameters
lowint or array-like of ints
Lowest (signed) integers to be drawn from the distribution (unless high=None, in which case this parameter is 0 and this value is used for high).

highint or array-like of ints, optional
If provided, one above the largest (signed) integer to be drawn from the distribution (see above for behavior if high=None). If array-like, must contain integer values

sizeint or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

dtypedtype, optional
Desired dtype of the result. Byteorder must be native. The default value is np.int64.

endpointbool, optional
If true, sample from the interval [low, high] instead of the default [low, high) Defaults to False

Returns
outint or ndarray of ints
size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.

Notes

When using broadcasting with uint64 dtypes, the maximum value (2**64) cannot be represented as a standard integer type. The high array (or low if high is None) must have object dtype, e.g., array([2**64]).




In [75]:
rng.integers(2, size=10)

array([1, 1, 0, 1, 1, 1, 0, 1, 0, 1])

In [76]:
rng.integers(1, size=10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [77]:
#Generate a 2 x 4 array of ints between 0 and 4, inclusive:

rng.integers(5, size=(2, 4))

array([[2, 4, 2, 4],
       [1, 0, 2, 2]])

In [78]:
#Generate a 1 x 3 array with 3 different upper bounds

rng.integers(1, [3, 5, 10])

array([1, 2, 4])

In [79]:
#Generate a 1 by 3 array with 3 different lower bounds

rng.integers([1, 5, 7], 10)

array([5, 5, 8])

In [80]:
#Generate a 2 by 4 array using broadcasting with dtype of uint8

rng.integers([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)

array([[ 8,  8,  8,  8],
       [11, 14, 10, 19]], dtype=uint8)

### numpy.random.random_sample (ranf and random.sample aliases)



*### numpy.random.random-
random.random(size=None)
Return random floats in the half-open interval [0.0, 1.0). Alias for random_sample to ease forward-porting to the new random API.*





random.random_sample(size=None)
Return random floats in the half-open interval [0.0, 1.0).


Results are from the “continuous uniform” distribution over the stated interval. To sample  multiply the output of random_sample by (b-a) and add a:

(b - a) * random_sample() + a
Note

New code should use the random method of a default_rng() instance instead; please see the Quick Start.

Parameters
sizeint or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

Returns
outfloat or ndarray of floats
Array of random floats of shape size (unless size=None, in which case a single float is returned).

See also

Generator.random
which should be used for new code.

       






In [81]:
np.random.random_sample()

0.401259693467627

In [82]:
type(np.random.random_sample())

float

In [83]:
np.random.random_sample((5,))

array([0.78926276, 0.88662003, 0.48737228, 0.38540362, 0.56930928])

In [84]:
#Three-by-two array of random numbers from [-5, 0):

5 * np.random.random_sample((3, 2)) - 5

       

array([[-2.59573615, -2.81638634],
       [-3.0938494 , -4.72410933],
       [-1.36905015, -0.4327126 ]])

### numpy.random.choice
random.choice(a, size=None, replace=True, p=None)
Generates a random sample from a given 1-D array

New in version 1.7.0.

Note

New code should use the choice method of a default_rng() instance instead; please see the Quick Start.

Parameters
a1-D array-like or int
If an ndarray, a random sample is generated from its elements. If an int, the random sample is generated as if it were np.arange(a)

sizeint or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

replaceboolean, optional
Whether the sample is with or without replacement. Default is True, meaning that a value of a can be selected multiple times.

p1-D array-like, optional
The probabilities associated with each entry in a. If not given, the sample assumes a uniform distribution over all entries in a.

Returns
samplessingle item or ndarray
The generated random samples

Raises
ValueError
If a is an int and less than zero, if a or p are not 1-dimensional, if a is an array-like of size 0, if p is not a vector of probabilities, if a and p have different lengths, or if replace=False and the sample size is greater than the population size

See also

randint, shuffle, permutation
Generator.choice
which should be used in new code

Notes

Setting user-specified probabilities through p uses a more general but less efficient sampler than the default. The general sampler produces a different sample than the optimized sampler even if each element of p is 1 / len(a).

Sampling random rows from a 2-D array is not possible with this function, but is possible with Generator.choice through its axis keyword.


In [85]:
#Generate a uniform random sample from np.arange(5) of size 3:
rng.choice(5, 3)
#This is equivalent to np.random.randint(0,5,3)

array([2, 1, 0])

In [86]:
#Generate a non-uniform random sample from np.arange(5) of size 3:
rng.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 3, 3])

In [87]:
#Generate a uniform random sample from np.arange(5) of size 3 without replacement:
rng.choice(5, 3, replace=False)
#This is equivalent to np.random.permutation(np.arange(5))[:3]

array([0, 2, 4])

In [88]:
#Generate a non-uniform random sample from np.arange(5) of size 3 without replacement:

rng.choice(5, 3, replace=False, p=[0.1, 0, 0.3, 0.6, 0])

array([2, 3, 0])

In [89]:
#Any of the above can be repeated with an arbitrary array-like instead of just integers. For instance:

aa_milne_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']
rng.choice(aa_milne_arr, 5, p=[0.5, 0.1, 0.1, 0.3])
      

array(['Christopher', 'Christopher', 'pooh', 'Christopher', 'pooh'],
      dtype='<U11')

### numpy.random.Generator.bytes¶

```random.Generator.bytes(length)```
Return random bytes. The parameter denotes the number of integers required in the return. The output returns as a string. 



In [90]:
# Demonstrates the ease of returning random bytes
rng.bytes(10)

b'\xe9\xfe\x7fJ\x14\xa8\xe5\xc8\r\x8c'

## Permutations

The permutations functions in Numpy  consist of 2 very similar functions: ```shuffle(x)``` and ```permutation (x)```. The documentation has changed on this slightly since the 1.21 release in June 2021 and now provides functionality to manipulate the sub-arrays by calling ```axis```.
Prior to the newest release of NumPy the method for calling these functions was through ```np.random.shuffle(x)``` or ```np.random.permutation(x)```; however since release 1.21 in June 2021 [7] the accepted method is now to import ```rng``` from the random package, as seen above, and use this in the function call instead. As of October 2021 the older method of calling this function is still working, but new users should be aware that this may become deprecated in the future.   


### Shuffle (x, axis = 0)
***
The shuffle function modifies an array sequence in-place by shuffling its contents. It should be noted that this function will only shuffle the first axis of a multi-dimensional array (ie an array with more than one sub-arrays) by default. Since June 2021. shuffle now uses ```axis``` as an argument to manipulate the sub-arrays, ie if axis is set at 0 then only the first dimension of arrays will shuffle around. However if it is set to 1 or any other sub-array level, then the first level will set as they were and it is only the values in the dimension called that will move. As this can be a difficult thing to abstractly visualise, I have laid out the following examples below to help visualise the dimensions. 





In [91]:
#Create a sample array from 0-9 inclusive 
arr= np.arange(10)
print (arr)

[0 1 2 3 4 5 6 7 8 9]


In [92]:
#Using the random.shuffle function.

rng.shuffle(arr)

print (arr) 

[7 8 1 0 2 4 3 9 6 5]


In [93]:
#Creating a 6 x 3 array to demonstrate the axis function

arr = np.arange(18).reshape((6, 3))

print (arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [94]:
#As there is no axis argument called, shuffle defaults to 0
rng.shuffle (arr, axis = 0)

print (arr)

[[ 6  7  8]
 [12 13 14]
 [ 9 10 11]
 [ 3  4  5]
 [15 16 17]
 [ 0  1  2]]


In [95]:
arr = np.arange(18).reshape((6, 3))

print (arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [96]:
rng.shuffle (arr, axis =1)

print (arr)

[[ 2  0  1]
 [ 5  3  4]
 [ 8  6  7]
 [11  9 10]
 [14 12 13]
 [17 15 16]]


### Permutation (x, axis = 0)
***
Is the act or process of changing the linear order of an ordered set. permutation(x) returns a random permutation of a sequence, or return a permuted range. If ```x``` is an array, it creates a copy of the original and shuffles those elements randomly. As with ```shuffle``` above, if it a multi-dimensional array then only the first dimension of the array is shuffled by default, however the use of ```axis``` will determine which array is shuffled, defaulting as axis 0. 

In [97]:
#arr is created from the example above. 
print (arr)


[[ 2  0  1]
 [ 5  3  4]
 [ 8  6  7]
 [11  9 10]
 [14 12 13]
 [17 15 16]]


In [98]:
#demonstrates the usage of permutation.
rng.permutation(arr)

array([[ 8,  6,  7],
       [17, 15, 16],
       [14, 12, 13],
       [11,  9, 10],
       [ 2,  0,  1],
       [ 5,  3,  4]])

In [99]:
#Create original array
arr= np.arange(18). reshape((6,3))
print (arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [100]:
#Demonstrate permutation on axis 0
rng.permutation (arr)

array([[12, 13, 14],
       [ 3,  4,  5],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [15, 16, 17],
       [ 6,  7,  8]])

In [101]:
#Demonstrate permutation on axis 1
rng.permutation (arr, axis =  1)

array([[ 1,  0,  2],
       [ 4,  3,  5],
       [ 7,  6,  8],
       [10,  9, 11],
       [13, 12, 14],
       [16, 15, 17]])

Note that in the example of permutation on axis 1 the positioning of the original numbers within each sub-array are the only thing that shuffled, leaving the positioning of the arrays in the overall list as it was when the object was originally created

Numpy’s random number routines produce pseudo random numbers using combinations of a BitGenerator to create sequences and a Generator to use those sequences to sample from different statistical distributions:

BitGenerators: Objects that generate random numbers. These are typically unsigned integer words filled with sequences of either 32 or 64 random bits.

Generators: Objects that transform sequences of random bits from a BitGenerator into sequences of numbers that follow a specific probability distribution (such as uniform, Normal or Binomial) within a specified interval.

Since Numpy version 1.17.0 the Generator can be initialized with a number of different BitGenerators. It exposes many different probability distributions. See NEP 19 for context on the updated random Numpy number routines. The legacy RandomState random number routines are still available, but limited to a single BitGenerator. See What’s New or Different for a complete list of improvements and differences from the legacy RandomState.

For convenience and backward compatibility, a single RandomState instance’s methods are imported into the numpy.random namespace, see Legacy Random Generation for the complete list.

# END
***

## References 

[1]: https://numpy.org/doc/stable/user/absolute_beginners.html#generating-random-numbers

[2]: https://stackoverflow.com/questions/7029993/differences-between-numpy-random-and-random-random-in-python

[3]: wes mckinney's book pg 120

[4]: https://www.sharpsightlabs.com/blog/numpy-random-choice/

[5]: https://www.analyticsvidhya.com/blog/2016/06/bayesian-statistics-beginners-simple-english/

[6]: https://numpy.org/doc/stable/reference/random/generated/numpy.random.shuffle.html

[7]: https://github.com/numpy/numpy/milestone/87

[8]: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.permutation.html#numpy.random.Generator.permutation

[9]: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.shuffle.html#numpy.random.Generator.shuffle



https://www.qualtrics.com/uk/experience-management/research/simple-random-sampling/




