" following assignment concerns the numpy.random package in Python [2]. You are
required to create a Jupyter [5] notebook explaining the use of the package, including
detailed explanations of at least five of the distributions provided for in the package.
There are four distinct tasks to be carried out in your Jupyter notebook.
1. Explain the overall purpose of the package.

    Explained in basic what the package is used for 
    
    
2. Explain the use of the “Simple random data” and “Permutations” functions.
    Permutations done


3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers."






# Numpy.random package 

***



In [14]:
import numpy as np

from numpy.random import default_rng
rng = default_rng()

NumPy is an open-source package used by data scientists and is the universal standard for working with, and manipulating numerical data in Python.The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.
There are a number of distinct functions within the package that perform a wide variety of high- level mathematical operations on multidimensional numerical arrays. In recent years Numpy has become particularly important for machine learning and deep learning, as these often involve large datasets of numerical data. The cleaning and reshaping of data is a large part of the workflow when dealing with these datasets and nupmy can provide some excellent tools to aid in this data manipulation[1]  [4]
Among these functions is the numpy.random package which can generate pseudo-random numbers. This is useful for many aspects of data analytics and machine learning projects, from randomly initialing weights in an artificial neural network, splitting data into random sets, or randomly shuffling your dataset, being able to generate random numbers (actually, repeatable pseudo-random numbers) is essential. **Random sampling is used in many tasks related to data analysis, statistics and other related fields, and is very commonly seen in probability, Bayesian statistics (“Bayesian statistics is a mathematical procedure that applies probabilities to statistical problems. It provides people the tools to update their beliefs in the evidence of new data.”), machine learning, among others  (Check this sentence out for improvements)**



While python's in-built random package ```random``` can generate values, for larger arrays ```numpy.random``` is preferred as it can sample more than one value at a time. This isn't so much an issue for smaller arrays, but for larger there is a noticeably faster time differential in most cases.[3] The numpy package can also offer a few extra probability distributions, such as binomial, commonly used in scientific research, as well as a couple of convenience functions for generating arrays of random data. The random.random library is a little more lightweight, and generally not considered suitable for scientific research or other kinds of work in statistics. [2] 


## Simple random data
*** 


**Simple random data in v1.21:** 


- **done** rand(d0, d1, …, dn)	Random values in a given shape.
- **done** numpy.random.Generator.standard_normal (d0, d1, …, dn)	Return a sample (or samples) from the “standard normal” distribution.
- **done** numpy.random.Generator.integers	Return random integers from low (inclusive) to high (exclusive).
- **done** numpy.random.Generator.random
- **Done** numpy.random.Generator.choice(a[, size, replace, p])	Generates a random sample from a given 1-D array
- **Done** numpy.random.Generator.bytes(length)	Return random bytes.
- **TO DO** numpy.random.Generator.normal

### numpy.random.rand
***
random.rand(d0, d1, ..., dn)
- Random values in a given multi-dimensional shape. 
- This a convenience function to aid in compatibility with Matlab function ```random_sample``` (a function that takes a tuple to specify output size.) 
- It creates an array of a given shape and populates it with random samples from a unifom distribution over [(0,1)]. 
- If no argument is given, a single float integer is returned. 
- The dimensions of the returned array must be positive






       
 

In [15]:
np.random.rand(3,2)

array([[0.6687104 , 0.61034669],
       [0.88859359, 0.03871408],
       [0.83167527, 0.18570586]])

### numpy.random.randn
***
random.randn(d0, d1, ..., dn)
- Return a sample (or samples) from the “standard normal” distribution.

- This is a convenience function to aid in compatibility with Matlab function ```standard_normal```. That function takes a tuple to specify the size of the output. 

- **New code should use the standard_normal method of a default_rng() instance instead. standard_normal takes a tuple in as its arguemtns

- If positive integer-like arguments are provided, ```randn``` generates an array from the shape provided in the arguments filled with random floats sampled from a standard normal (Gaussian) distribution of mean 0 and variance 1.
- A single float randomly sampled from the distribution is returned if no argument is provided.

### - To look at:
    - normal
            Also accepts mu and sigma arguments.

    - Generator.standard_normal
            which should be used for new code.
            
            
## New code from 1.21

numpy.random.Generator.standard_normal
method

random.Generator.standard_normal(size=None, dtype=np.float64, out=None)
Draw samples from a standard Normal distribution (mean=0, stdev=1).

Parameters
sizeint or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

dtypedtype, optional
Desired dtype of the result, only float64 and float32 are supported. Byteorder must be native. The default value is np.float64.

outndarray, optional
Alternative output array in which to place the result. If size is not None, it must have the same shape as the provided size and must match the type of the output values.

Returns
outfloat or ndarray
A floating-point array of shape size of drawn samples, or a single sample if size was not specified.

See also

normal
Equivalent function with additional loc and scale arguments for setting the mean and standard deviation.

Notes

For random samples from , use one of:

mu + sigma * rng.standard_normal(size=...)
rng.normal(mu, sigma, size=...)





In [16]:
np.random.randn()

0.36282647390690914

In [17]:
#Two-by-four array of samples from N(3, 6.25):

3 + 2.5 * np.random.randn(2, 4)

array([[-0.49064393,  2.65226491,  4.88808249,  2.13151736],
       [ 4.22204069,  5.5881305 ,  2.41550773,  2.89788225]])

### numpy.random.Generator.integers
***

numpy.random.Generator.integers(low, high=None, size=None, dtype=np.int64, endpoint = False)
- Return random integers from low (inclusive) to high (exclusive) 
- If endpoint is True high is inclusive also

- Return random integers from the “discrete uniform” distribution of the specified dtype. If high is None (the default), then results are from 0 to low.

### Parameters

- low: int or array-like of ints
Lowest (signed) integers to be drawn from the distribution. If high is None, low is used for high. 

- high: int or array-like of ints, optional
If provided, one above the largest (signed) integer to be drawn from the distribution. If array-like, must contain integer values

- size: int or tuple of ints, optional
Sets output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If not specified a single value is returned.

- dtype: dtype, optional
Desired dtype of the result. Byteorder must be native. The default value is np.int64.

- endpoint: bool, optional
Default is false, so sample is low (inclusive) to high (exclusive). If true, sample is low (inclusive) to high (inclusive)

-Returns: 
size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.





In [18]:
rng.integers(2, size=10)

array([0, 0, 0, 1, 1, 0, 0, 0, 1, 1])

In [19]:
rng.integers(0,10, size=10, endpoint = True)

array([0, 7, 8, 7, 1, 5, 6, 0, 4, 6])

In [20]:
#Generate a 2 x 4 array of ints between 0 and 4, inclusive:

rng.integers(5, size=(2, 4))

array([[0, 4, 2, 4],
       [2, 4, 3, 1]])

In [21]:
#Generate a 1 x 3 array with 3 different upper bounds

rng.integers(1, [3, 5, 10])

array([2, 1, 9])

In [22]:
#Generate a 1 by 3 array with 3 different lower bounds

rng.integers([1, 5, 7], 10)

array([8, 9, 7])

In [23]:
#Generate a 2 by 4 array using broadcasting with dtype of uint8

rng.integers([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)

array([[ 2,  7,  6,  8],
       [11, 11, 13, 15]], dtype=uint8)

### numpy.random.Generator.random
numpy.random.Generator.random(size=None, dtype=np.float64, out=None)
Return random floats in the half-open interval [0.0, 1.0).


- numpy.random.random (size = None)
    - Return random floats in the half-open interval [0.0, 1.0). 
    - Alias for random_sample to ease forward-porting to the new random API





- random.random_sample(size=None). 

- Results are from the “continuous uniform” distribution over the stated interval. 


Parameters
- size: int or tuple of ints, optional. Sets output shape. If not set, default is None, and so a single value is returned

- dtype:dtype, optional
    - Desired dtype of the result, only float64 and float32 are supported. Byteorder must be native. The default value is np.float64.
- out:ndarray, optional
    - Alternative output array in which to place the result. If size is not None, it must have the same shape as the provided size and must match the type of the output values.
    
Returns
- Array of random floats of shape ```size``` (unless size=None, in which case a single float is returned).






In [24]:
rng.random()

0.8300549328438728

In [25]:
type(rng.random())

float

In [26]:
rng.random((5,))

array([0.21728889, 0.27428059, 0.20540295, 0.83282441, 0.93709451])

In [27]:
#Three-by-two array of random numbers from [-5, 0):

5 * rng.random((3, 2)) - 5

       

array([[-4.75140742, -3.72378876],
       [-4.09146814, -4.14885204],
       [-4.85770279, -0.5032998 ]])

### numpy.random.Generator.choice
numpy.random.Generator.choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)¶
Generates a random sample from a given array


Parameters
- a{array_like, int}
If an ndarray, a random sample is generated from its elements. If an int, the random sample is generated from np.arange(a).

- size{int, tuple[int]}, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn from the 1-d a. If a has more than one dimension, the size shape will be inserted into the axis dimension, so the output ndim will be a.ndim - 1 + len(size). Default is None, in which case a single value is returned.

- replace:bool, optional
Whether the sample is with or without replacement. Default is True, meaning that a value of a can be selected multiple times.

- p: 1-D array_like, optional
The probabilities associated with each entry in a. If not given, the sample assumes a uniform distribution over all entries in a.

- axis:int, optional
The axis along which the selection is performed. The default, 0, selects by row.

- shuffle: bool, optional
Whether the sample is shuffled when sampling without replacement. Default is True, False provides a speedup.

Returns
samples: single item or ndarray- The generated random samples

Raises
ValueError:
If a is an int and less than zero, if a or p are not 1-dimensional, if a is an array-like of size 0, if p is not a vector of probabilities, if a and p have different lengths, or if replace=False and the sample size is greater than the population size





In [28]:
#Generate a uniform random sample from np.arange(5) of size 3:
rng.choice(5, 3)
#This is equivalent to np.random.randint(0,5,3)

array([2, 1, 2])

In [29]:
#Generate a non-uniform random sample from np.arange(5) of size 3:
rng.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])

array([0, 3, 3])

In [30]:
#Generate a uniform random sample from np.arange(5) of size 3 without replacement:
rng.choice(5, 3, replace=False)
#This is equivalent to np.random.permutation(np.arange(5))[:3]

array([3, 0, 4])

In [31]:
#Generate a non-uniform random sample from np.arange(5) of size 3 without replacement:

rng.choice(5, 3, replace=False, p=[0.1, 0, 0.3, 0.6, 0])

array([2, 3, 0])

In [32]:
#Any of the above can be repeated with an arbitrary array-like instead of just integers. For instance:

aa_milne_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']
rng.choice(aa_milne_arr, 5, p=[0.5, 0.1, 0.1, 0.3])
      

array(['Christopher', 'Christopher', 'pooh', 'Christopher', 'pooh'],
      dtype='<U11')

### numpy.random.Generator.bytes¶

```numpy.random.Generator.bytes(length)```
Return random bytes. The parameter denotes the number of integers required in the return. The output returns as a string. 



In [33]:
# Demonstrates the ease of returning random bytes
rng.bytes(10)

b'\t\xcfo\xaaD\xe3a7\xde\xc1'

## Permutations

The permutations functions in Numpy  consist of 2 very similar functions: ```shuffle(x)``` and ```permutation (x)```. The documentation has changed on this slightly since the 1.21 release in June 2021 and now provides functionality to manipulate the sub-arrays by calling ```axis```.
Prior to the newest release of NumPy the method for calling these functions was through ```np.random.shuffle(x)``` or ```np.random.permutation(x)```; however since release 1.21 in June 2021 [7] the accepted method is now to import ```rng``` from the random package, as seen above, and use this in the function call instead. As of October 2021 the older method of calling this function is still working, but new users should be aware that this may become deprecated in the future.   


### Shuffle (x, axis = 0)
***
The shuffle function modifies an array sequence in-place by shuffling its contents. It should be noted that this function will only shuffle the first axis of a multi-dimensional array (ie an array with more than one sub-arrays) by default. Since June 2021. shuffle now uses ```axis``` as an argument to manipulate the sub-arrays, ie if axis is set at 0 then only the first dimension of arrays will shuffle around. However if it is set to 1 or any other sub-array level, then the first level will set as they were and it is only the values in the dimension called that will move. As this can be a difficult thing to abstractly visualise, I have laid out the following examples below to help visualise the dimensions. 





In [34]:
#Create a sample array from 0-9 inclusive 
arr= np.arange(10)
print (arr)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
#Using the random.shuffle function.

rng.shuffle(arr)

print (arr) 

[8 3 1 6 4 7 2 0 9 5]


In [36]:
#Creating a 6 x 3 array to demonstrate the axis function

arr = np.arange(18).reshape((6, 3))

print (arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [37]:
#As there is no axis argument called, shuffle defaults to 0
rng.shuffle (arr, axis = 0)

print (arr)

[[ 6  7  8]
 [12 13 14]
 [15 16 17]
 [ 0  1  2]
 [ 9 10 11]
 [ 3  4  5]]


In [38]:
arr = np.arange(18).reshape((6, 3))

print (arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [39]:
rng.shuffle (arr, axis =1)

print (arr)

[[ 1  0  2]
 [ 4  3  5]
 [ 7  6  8]
 [10  9 11]
 [13 12 14]
 [16 15 17]]


### Permutation (x, axis = 0)
***
Is the act or process of changing the linear order of an ordered set. permutation(x) returns a random permutation of a sequence, or return a permuted range. If ```x``` is an array, it creates a copy of the original and shuffles those elements randomly. As with ```shuffle``` above, if it a multi-dimensional array then only the first dimension of the array is shuffled by default, however the use of ```axis``` will determine which array is shuffled, defaulting as axis 0. 

In [40]:
#arr is created from the example above. 
print (arr)


[[ 1  0  2]
 [ 4  3  5]
 [ 7  6  8]
 [10  9 11]
 [13 12 14]
 [16 15 17]]


In [41]:
#demonstrates the usage of permutation.
rng.permutation(arr)

array([[ 1,  0,  2],
       [13, 12, 14],
       [16, 15, 17],
       [10,  9, 11],
       [ 4,  3,  5],
       [ 7,  6,  8]])

In [42]:
#Create original array
arr= np.arange(18). reshape((6,3))
print (arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [43]:
#Demonstrate permutation on axis 0
rng.permutation (arr)

array([[ 6,  7,  8],
       [ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [ 0,  1,  2],
       [12, 13, 14]])

In [44]:
#Demonstrate permutation on axis 1
rng.permutation (arr, axis =  1)

array([[ 2,  0,  1],
       [ 5,  3,  4],
       [ 8,  6,  7],
       [11,  9, 10],
       [14, 12, 13],
       [17, 15, 16]])

Note that in the example of permutation on axis 1 the positioning of the original numbers within each sub-array are the only thing that shuffled, leaving the positioning of the arrays in the overall list as it was when the object was originally created

Numpy’s random number routines produce pseudo random numbers using combinations of a BitGenerator to create sequences and a Generator to use those sequences to sample from different statistical distributions:

BitGenerators: Objects that generate random numbers. These are typically unsigned integer words filled with sequences of either 32 or 64 random bits.

Generators: Objects that transform sequences of random bits from a BitGenerator into sequences of numbers that follow a specific probability distribution (such as uniform, Normal or Binomial) within a specified interval.

Since Numpy version 1.17.0 the Generator can be initialized with a number of different BitGenerators. It exposes many different probability distributions. See NEP 19 for context on the updated random Numpy number routines. The legacy RandomState random number routines are still available, but limited to a single BitGenerator. See What’s New or Different for a complete list of improvements and differences from the legacy RandomState.

For convenience and backward compatibility, a single RandomState instance’s methods are imported into the numpy.random namespace, see Legacy Random Generation for the complete list.

# END
***

## References 

[1]: https://numpy.org/doc/stable/user/absolute_beginners.html#generating-random-numbers

[2]: https://stackoverflow.com/questions/7029993/differences-between-numpy-random-and-random-random-in-python

[3]: wes mckinney's book pg 120

[4]: https://www.sharpsightlabs.com/blog/numpy-random-choice/

[5]: https://www.analyticsvidhya.com/blog/2016/06/bayesian-statistics-beginners-simple-english/

[6]: https://numpy.org/doc/stable/reference/random/generated/numpy.random.shuffle.html

[7]: https://github.com/numpy/numpy/milestone/87

[8]: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.permutation.html#numpy.random.Generator.permutation

[9]: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.shuffle.html#numpy.random.Generator.shuffle



https://www.qualtrics.com/uk/experience-management/research/simple-random-sampling/




